### PR TITLE
feat: add support for diagnostic.relatedInformation

### LINKED ISSUE #80: Add support for new diagnostic.relatedInformation

### PR DESCRIPTION
**Pull request by Mayank1791989**
closes #80

### CODE REVIEW

**Comment by thymikee** [comment]
And a screenshot:

screen shot 2018-06-25 at 23 53 45

Would be great to get this in and publish soon :)

**Comment by macrozone** [comment]
this would be a gift for vscode users!

**Comment by wbinnssmith** [comment]
Sorry for the delay on this, all. Going to merge and publish this now.

@amasad

**Comment by amasad** [comment]
Thanks!

**Pull request merged**
